//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CI.ClinicalTrials.RegressionTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CI.ClinicalTrials.RegressionTest.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the following errors before continuing:
        ///A trial can only be marked as &apos;Classified&apos; or &apos;In Review&apos; once it has been verified.
        ///A trial can only have a Classification, once it has been verified..
        /// </summary>
        internal static string ClassificationError {
            get {
                return ResourceManager.GetString("ClassificationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Failures must be a positive number or 0
        ///New Enrollments must be a positive number or 0.
        ///Active On Intervention must be a positive number or 0.
        ///Follow-up must be a positive number or 0.
        ///Discontinued must be a positive number or 0..
        /// </summary>
        internal static string EmptyParticipantErrorMessage {
            get {
                return ResourceManager.GetString("EmptyParticipantErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site target must not be left blank.
        ///Principal Investigator must not be left blank.
        ///Key Contact must not be left blank.
        ///Select an option for Site Responsible.
        /// </summary>
        internal static string EmptyTrialDetailMessage {
            get {
                return ResourceManager.GetString("EmptyTrialDetailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a trial has been added to My Site Trials list in error without any underlying data, you can remove it. Contact clinical.trials@cancerinstitute.org.au for queries about removing trials from your list..
        /// </summary>
        internal static string RemoveTrial_MySiteTrial {
            get {
                return ResourceManager.GetString("RemoveTrial_MySiteTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial data has been signed off for the current report period..
        /// </summary>
        internal static string SignedOffTrialData {
            get {
                return ResourceManager.GetString("SignedOffTrialData", resourceCulture);
            }
        }
    }
}
